### ISSUE TITLE
Ship additional net461 assembly?

### ISSUE THREAD

**Issue by chuseman** [prometheus-net/prometheus-net#155]
We've got several older projects that still target .NET 4.6.1 and I'd like to bring in prometheus-net, but I'm unable to because of compilation issues.

For the unaware, there are known issues with .NET 4.6.1-4.7.1 for .NET Standard 2.0 references. [Microsoft's guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#multi-targeting) is to additionally target `net461` when targeting `netstandard2.0` as a workaround.

If there's interest, I'd be happy to contribute a PR for what I can. Specifically, I'd update the two `csproj` files as well as the `nuspec` files to copy both sets of libraries. Unfortunately a lot of the logic lives in the Azure DevOps Pipeline definitions for the Build and Release so I couldn't update those (unless you switch over to YAML configuration first).

**Comment by sandersaares** [comment]
Do I understand it right that this would involve publishing different binaries, one for net461 and one for netstandard2.0? If so, I would not be willing to make this change.

The reason is that I deliberately try to keep the build and publishing pipeline minimally complex, as it is an easy place for "taxes" to incur that would have a negative effect on motivating quick publishing of fixes and updates (having to make and check different builds etc). As such, I do not accept changes into the library that would complicate the build process by outputting multiple sets of binaries (or by requiring multiple code paths for different targets).

While automation can help reduce such taxes, I would only consider this if targeting modern platforms that require such deviations (e.g. .NET Core 3.0, though I hope it will not) and not in case of legacy platforms that can (in theory) be upgraded from.

I would be interested to learn more about the specific issues you experienced - if not for else, then maybe to add to the readme so other users could be saved some effort in troubleshooting.

**Comment by chuseman** [comment]
Trust me, I understand not wanting to bend over backward to support legacy platforms :) I wish it were an option for me.

Maybe it would be best if I describe exactly what I'm proposing. I'm just wanting an additional assembly in the `prometheus-net` NuGet package. It would live in the `lib/net461` folder in the package (next to the existing `lib/netstandard2.0` folder).

Multi-targeting is super easy now; you'd switch this line:

https://github.com/prometheus-net/prometheus-net/blob/d29ca370b1d1142eaea87f144e44ea8a486e3e9f/Prometheus.NetStandard/Prometheus.NetStandard.csproj#L4

To have multiple target frameworks (note the plural TargetFramework**s** node name):

```xml
<TargetFrameworks>net461;netstandard2.0</TargetFrameworks>
```

This would then create a `bin/Release/net461` folder next to `bin/Release/netstandard2.0`. I can see in the [last build log where these files are copied in preparation to be packaged](https://dev.azure.com/prometheus-net/prometheus-net/_build/results?buildId=23&view=logs&jobId=275f1d19-1bd8-5591-b06b-07d489ea915a&taskId=f3d94f14-b8a6-5b49-b005-03f073aba73c&lineStart=10&lineEnd=14&colStart=1&colEnd=1). This would have to be updated to keep the folders separate.

Then for packaging, `prometheus-net.nuspec` would need to be updated to place the built assemblies in their own appropriate folders inside the package:

https://github.com/prometheus-net/prometheus-net/blob/d29ca370b1d1142eaea87f144e44ea8a486e3e9f/Resources/Nuspec/prometheus-net.nuspec#L21-L22

I don't expect that there would be any other changes required, since `netstandard2.0` is already the target framework and there aren't any dependencies.

**Comment by sandersaares** [comment]
Okay, that sounds effortless enough to be worth it. However, when I attempt to do this change in the csproj (`<TargetFrameworks>net461;netstandard2.0</TargetFrameworks>`) I start getting compile errors:

```
1>------ Rebuild All started: Project: Prometheus.NetStandard, Configuration: Debug Any CPU ------
1>MetricPusher.cs(5,18,5,22): error CS0234: The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?)
1>MetricPusherOptions.cs(3,18,3,22): error CS0234: The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?)
1>ChildBase.cs(58,74,58,90): error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported
1>Labels.cs(46,37,46,53): error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported
1>MetricPusher.cs(19,31,19,41): error CS0246: The type or namespace name 'HttpClient' could not be found (are you missing a using directive or an assembly reference?)
1>MetricPusherOptions.cs(21,21,21,31): error CS0246: The type or namespace name 'HttpClient' could not be found (are you missing a using directive or an assembly reference?)
1>MetricPusher.cs(69,33,69,43): error CS0246: The type or namespace name 'HttpClient' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "Prometheus.NetStandard.csproj" -- FAILED.
1>Prometheus.NetStandard -> C:\Source\prometheus-net\Prometheus.NetStandard\bin\Debug\netstandard2.0\Prometheus.NetStandard.dll
```

What am I missing here?

**Comment by chuseman** [comment]
> What am I missing here?

Two additional things I didn't consider (just for .NET 4.6.1):
- A .NET Framework reference to `System.Net.Http`
- A NuGet reference for `System.ValueTuple`

I've opened a PR for the csproj changes. Note that it doesn't update the nuspec -- that'll also require a build definition change to copy the additional `net461` build output.

**Comment by sandersaares** [comment]
This is now available in NuGet package version 3.2.0-pre-000032-9939133. Please let me know if everything seems to be in order. Thanks for the PR!

**Comment by sandersaares** [comment]
It seems to work when I try it (although I am not sure what exactly was the error it fixed), so I will consider this closed and ready for publishing. Please feel free to comment if something seems wrong.

**Comment by krisavi** [comment]
It seems the NuGet package 3.3.0 is not compatible with .Net Framework 4.6.1 
The readme file states it works on 4.6.1, but it does not seem to work on it. 
I have .Net Framework 4.7.0 installed and it seems to give error about System.ValueTuple.

`System.TypeInitializationException: The type initializer for 'Prometheus.Metrics' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.`

**Comment by sandersaares** [comment]
@krisavi can you post a full sample project that reproduces the issue? I am unable to reproduce the error you experience.

The library is intended to be compatible with 4.6.1, so if it is not perhaps something can be adjusted. It is true, however, that old .NET Framework versions are rarely tested, so we must rely on users to provide good repro cases that clearly illustrate the problem.

**Comment by krisavi** [comment]
Hey, I got mine solved... It seems I had to download separate nuget package for System.ValueTuple to get it work. 
It was quite basic project, added to 4.6.1 framework project Prometheus, it's gauges and their data population and metrics server.

**Comment by sandersaares** [comment]
I would be happy to try get this resolved already in packaging of prometheus-net but I really need a full project that reproduces the issue. Maybe it is something specific to my development environment but it just seems to work when I try some basic tests like that.
